title: Sena Perdiana
description: Random stuff
author: Sena Perdiana
email: senaferdy79@gmail.com
phone: 0
github: https://github.com/helenaferdy
about: A 2020 graduate majoring Computer Systems with great interest in Network Engineering and Information Security.
disqus_shortname: Networking and Information Security
avatar_url: /static/img/me.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:    
    - icon: fa-github
      link: "https://github.com/helenaferdy"
    - icon: fa-linkedin
      link: "https://linkedin.com/in/senaperdiana"
    - icon: fa-instagram
      link: "https://instagram.com/senafrd/"
    - icon: fa-facebook
      link: "https://facebook.com/helenaferdy"
    - icon: fa-twitter
      link: "https://twitter.com/helenaferdy"
    - icon: fa-steam
      link: "https://steamcommunity.com/id/senaferdy79"

share:
  twitter_username: helenaferdy
  # fb_appid: 1749788565247320

# urls:
#     - text: About Me
#       url: /about/
#     - text: Projects
#       url: /projects/
#     - text: Blogs
#       url: /blogs/
#     - text: XML Feed
#       url: /feed.xml
# url: "http://localhost:4000"
url: "https://helenaferdy.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
